source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.18'
# Use Puma as the app server
gem 'puma', '~> 3.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtime
gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'jquery-turbolinks'
gem 'jquery-ui-rails'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Static style guide for ruby
gem 'rubocop', '~> 0.42.0', require: false
# file atachment libary for active record
gem 'paperclip', '~> 5.0.0'
gem 'aws-sdk', '~> 2.3'
# powerful ruby ffmpeg wrapper for reading metadata and transcoding movies
gem 'streamio-ffmpeg'

# For cross-origin requests
gem 'rack-cors'

#front end gems
gem 'bootstrap'
gem 'awesome_print'
gem 'font-awesome-rails'

# pagination gem
gem 'alphabetical_paginate'

#Ask faustino if necesarry
gem 'frontend-generators', '0.1.1'

# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

#Use devise for login
gem 'devise'
gem 'devise_token_auth'
gem 'omniauth'
gem 'hashie'

#Use sendgrid for mail confirmation
gem 'sendgrid'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

#Gem for graphs
gem 'chart-js-rails'

# Gem for forms
gem 'simple_form'
gem 'faker'

# Gem for graphs
gem 'chartkick'

# Gem for calendar
gem 'fullcalendar-rails'
gem 'momentjs-rails'


# Gem for dates
gem 'chronic'
gem 'switchery-rails'
gem 'bootstrap3-datetimepicker-rails', '~> 4.17.42'

#Gem for variables in javascript
gem 'gon'

#aysnc loading
gem 'remotipart'

#Gem for scheduling mails
gem 'sidekiq'